#!/bin/bash

# Turn on HTB VPN Connection
nmcli connection up 25edc69f-382b-422c-b696-68a5f0b433f7
# Remove default route to HTB to allow Internet access in Linux
sudo route del -net default gw 10.10.16.1 netmask 0.0.0.0 dev tun0
